version: "3"
services:

  app:
    build: .
    container_name: app
    networks:
      - localnetwork
    tty: true
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    hostname: "mysql"
    container_name: mysql
    networks:
      - localnetwork
    restart: always
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      - MYSQL_PORT=${MYSQL_PORT}
#      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

volumes:
  data-volume:

networks:
  localnetwork:
    driver: bridge
